### ISSUE TITLE
Right portlet of 

### ISSUE THREAD

**Issue by dgroos** [quintagroup/quintagroup.theme.sunrain#2]
Using Products.QuillsEnabled 1.8a1 (also  quills.app 1.8a1) and SunRain Theme 6.2 + SunRain Policy 1.0 on a plone 4.3.3 site.

Upon creating a page in a blog-activated folder (that is, creating a blog post in one's blog), the right portlet cuts through and obfiscates important areas of the page as shown in the screenshot below. Current work around is to toggle fullscreen editing screen but it doesn't look as professional and telling students to do this adds further complexity.

![ss_540](https://cloud.githubusercontent.com/assets/4097759/4435077/472d1a0c-4733-11e4-81c2-0ef841fd29cc.png)

**Comment by romabor93** [comment]
SunRain theme tested only with this products (MegaMenu, Blogs, Tag Cloud, Carousel, Portlet Widget, Form Widget, Drop-down menu, Multilingual support) but do not support Products.QuillsEnabled

**Comment by romabor93** [comment]
We can't confirm the issue with  Products.QuillsEnabled 1.8a1 (also quills.app 1.8a1) and SunRain Theme 6.2 + SunRain Policy 1.0 on a plone 4.3.3 site.
