### ISSUE TITLE
Sunrain or dropdown issue?

### ISSUE THREAD

**Issue by dgroos** [quintagroup/quintagroup.theme.sunrain#6]
When I use sunrain theme (7.2.3) with webcouturier.dropdownmenu (just upped to v. 3.0.1) on plone 5.0.6 there is an issue moving the cursor from a folder menu item to its child. In the screen shot you can see there is a thin white space between menu and sub menu. When moving the mouse at regular speed between these menus, apparently this thin space is interpreted by firefox as not part of either menu and thus the menus close down, very frustrating. Only by moving quite rapidly between the 2 menus does this not happen. Of course, this might be a webcouturier.dropdownmenu issue. Thanks (again and again) for this great theme--it's been my favorite for many years.
![sss-254](https://cloud.githubusercontent.com/assets/4097759/22000247/bec0aa40-dc03-11e6-9c99-2506343b814a.png)

**Comment by LesukS** [comment]
Fix this bug in 7.2.5 release
